accounts/urls.py
from django.urls import path 
from . import views
app_name = 'accounts'
urlpatterns = [
    path('' , views.index , name="index"),
    path('login/' , views.signin , name="login" ),
    path('register/' , views.signup , name="register" ),
    path('my_profile' , views.profile_page , name="profile"),
    path('logout/' , views.logout_page , name="logout"),
    path('update/' , views.update_profile_page , name="update"),
    path('doctor_details/<str:slug>/' , views.doctor_details , name="doctor_details"),
]

project/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),

]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import post_save

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User , related_name="user" , on_delete=models.CASCADE)
    title = models.CharField(max_length=30, blank=True , null=True)
    description = models.TextField(max_length=200, blank=True , null=True)
    subtitle = models.CharField(max_length=30, blank=True , null=True)
    job_name = models.CharField(max_length=30, blank=True , null=True)
    image = models.ImageField(upload_to='profile/', blank=True , null=True)
    address = models.CharField(max_length=30, blank=True , null=True)
    provenece = models.CharField(max_length=30, blank=True , null=True)
    working_hour = models.IntegerField( blank=True , null=True)
    number = models.CharField(max_length=20, blank=True , null=True)
    price = models.IntegerField( blank=True , null=True)
    slug = models.SlugField(max_length=30, blank=True , null=True)
    working_time = models.IntegerField( blank=True , null=True)
    department = models.CharField(max_length=30 , null=True , blank=True)

    def __str__(self):
        return str(self.user.username)
    
def save(self, *args, **kwargs):
    self.slug = slugify(self.title)
    super(Profile, self).save(*args, **kwargs)
        


def create_profile(sender , created , instance ,**kwargs):
    if created:
        Profile.objects.create(user=instance)

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile



class LoginForm(forms.ModelForm):
    username = forms.CharField(label="الاسم")
    password = forms.CharField(label= "كلمه المرور", widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username' , 'password']



class RegisterForm(UserCreationForm):
    username = forms.CharField(label="الاسم")
    email = forms.EmailField(label="الايميل")
    password1 = forms.CharField(label= "كلمه المرور", widget=forms.PasswordInput)    
    password2 = forms.CharField(label= "تاكيد كلمه المرور", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username' , 'email' , 'password1' , 'password2']
    


class UpdateProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user' , 'slug' , 'created_at']

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse , HttpResponseRedirect
from .models import Profile
from .forms import LoginForm , RegisterForm , UpdateProfile
from django.urls import reverse
from django.contrib.auth import authenticate , login , logout
from .filter import Filter
from django.core.paginator import Paginator
# Create your views here.


# fucntion  home page 
def index(request):
    index = Profile.objects.all()
    # filter 
    myFliter = Filter(request.GET , queryset=index)
    index = myFliter.qs
    paginator = Paginator(index , 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request , 'accounts/index.html' , {
        'doctor':page_obj , 'filter':myFliter
    })


# function login page
def signin(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request , username=username ,password=password)
        if user is not None :
            login(request , user)
            return HttpResponseRedirect(reverse('accounts:index'))

    else:
        form = LoginForm()
    return render(request , 'accounts/login.html' , {
        "form":form
    })

# function to register in this website 
def signup(request):
    if request.method == 'POST':
        form2 = RegisterForm(request.POST)
        if form2.is_valid():
            form2.save()
            return HttpResponseRedirect(reverse('accounts:login'))
            # username = form2.cleaned_data['username']
            # password = form2.cleaned_data['password1']
            # user = authenticate(username=username , password=password)
            # if user is not None:
            #     login(request , user)
            #     return HttpResponseRedirect(reverse('accounts:index'))
    else:
        form2 = RegisterForm()
    return render(request , 'accounts/signup.html' , {
        'forms':form2
    })


# function to display doctor information
def doctor_details(request , slug):
    doctors =  Profile.objects.get(slug=slug)
    return render(request , 'accounts/doctors_detail.html' , {
        'detail':doctors
    })


# function to display your profile
def profile_page(request):
    return render(request , 'accounts/profile.html' , {

    })



#function to update profile page
def update_profile_page(request):
    if request.method == 'POST':
        update = UpdateProfile(request.POST , request.FILES , instance=request.user )
        if update.is_valid() :
            update.save()
            return HttpResponseRedirect(reverse('accounts:profile'))

    else:
        update = UpdateProfile()
    return render(request , 'accounts/updata_profile.html' , {
        'update':update
    })


# function to logout from this page 
def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:index'))

accounts/templates/accounts/doctors_detail.html
{% extends 'base.html' %}
{% load static  %}
{% block body %}
<div dir="rtl">
    <!-- Search -->
    <div class="catagory_area ">
        <div class="container" style="margin-top: 10rem">

        </div>
    </div>
    <!-- endsearch -->

<div class="job_details_area">
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="job_details_header">
                <div class="single_jobs white-bg d-flex justify-content-between">
                    <div class="jobs_left d-flex align-items-center">
                        <div >
                            {% if detail.image %}
                            <img class="img-circle" src="{{ detail.image.url }}" alt="" width="100" height="100">

                            {% else %}
                            <img class="img-circle" src="{% static 'img/candiateds/2.png' %}" alt="" width="100" height="100">

                            {% endif %}
                            
                        </div>
                        <div class="jobs_conetent">
                            <a href="#" ><h4>{{ detail.title }}</h4></a>
                            <div class="links_locat d-flex align-items-center">
                                <div class="location">
                                    <p> <i class="fa fa-map-marker"></i> {{ detail.address }}  , {{ detail.provenece }}  </p>
                                </div>
                                <div class="location">
                                    <p> <i class="fa fa-clock-o"></i>  وقت الانتظار {{ detail.working_time }} دقيقه</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="jobs_right">
                        <div class="apply_now">
                            <a class="boxed-btn3" href="">حجز كشف</a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="descript_wrap white-bg">
                <div class="single_wrapp">
                    <h3>نبذه عن الدكتور</h3>
                </div>
                <div class="white-card white-card-inner">
                    <div class="single_wrap" style="margin-top: 10px;">
                        <h4>معلومات عن الدكتور</h4>
                        <ul>
                            <p>  {{ detail.description }} </p>
                        </ul>
                    </div>
                </div>
                <div class="single_wrap">
                    <h4>خدمات الدكتور :</h4>
                    <ul>
                        <p class="tagitem disable-click pull-left mr-4" style="background-color: #f5f5f5;
                        color: #808184;"> {{ detail.department }}
                        </p>
                    </ul>
                    <br>
                </div>
                <div class="single_wrap">
                    <h4>صور العيادة :</h4>
                            <img class="image_clinic" src="{% static 'img/candiateds/2.png' %}" alt="" >
                            <img class="image_clinic" src="{% static 'img/candiateds/2.png' %}" alt="" >
                            <img class="image_clinic" src="{% static 'img/candiateds/2.png' %}" alt="" >
                    


                </div>
            </div>

    <!-- comments -->
    <div class="section-row">
 
    </div>
    <!-- /comments -->                    
    <div class="apply_job_form white-bg">
    </div>
        </div>
        <div class="col-lg-4">
            <div class="job_sumary">
                <div class="summery_header">
                    <h3>معلومات عن الدكتور </h3>
                </div>
                <div class="job_content">
                    <ul>
                        <li>  انضم إلينا : <span style="color: blue;"></span></li>
                        <li> الكشف : <span style="color: blue;"> جنية</span> {{ detail.price }} </li>
                        <li> رقم الهاتف  : <span style="color: blue;"></span> {{ detail.number  }} </li>
                        <li>عدد ساعات العمل : <span style="color: blue;"> ساعات</span> {{ detail.working_hour  }} </li>
                    </ul>
                    
                </div>
            </div>
            <div class="share_wrap d-flex">
                <span>شارك الصفحه :</span>
                <ul>
                    <li><a href=""> <i class="fa fa-facebook"></i></a> </li>
                    <li><a href=""> <i class="fa fa-google-plus"></i></a> </li>
                    <li><a href=""> <i class="fa fa-twitter"></i></a> </li>
                    <li><a href=""> <i class="fa fa-envelope"></i></a> </li>
                </ul>
            </div>
            <div class="job_location_wrap">
                <div class="job_lok_inner">
                    <div id="map" style="height: 200px;"></div>
                    <script>
                        function initMap() {
                        var uluru = {lat: -25.363, lng: 131.044};
                        var grayStyles = [
                            {
                            featureType: "all",
                            stylers: [
                                { saturation: -90 },
                                { lightness: 50 }
                            ]
                            },
                            {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                        ];
                        var map = new google.maps.Map(document.getElementById('map'), {
                            center: {lat: -31.197, lng: 150.744},
                            zoom: 9,
                            styles: grayStyles,
                            scrollwheel:  false
                        });
                        }
                        
                    </script>
                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                    
                    </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock body %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div dir="rtl">
    <!-- Search -->
    <div class="catagory_area ">
<div class="container " style="margin-top: 10rem">
            <div class=" single_text">
                <h2>احجز مع
                    أفضل دكتور في مصر</h3>
                <h3>احجز اونلاين او كلم  ١٧٧٥۸</h4>
                <h4>١٦٠٠٠ دكتور -٤٠٠٠ استاذ واستشاري - اكثر من ۲٠ تخصص</h5>
                <br>
            </div>
            <form  method="GET">
            <div class="row cat_search" >
                {% csrf_token %}
                {{ filter.form }}
                
                <div class="col-lg-3 col-md-12">
                    <div class="job_btn">
                        <input type="submit" class="boxed-btn3" value="ابحث هنا">
                    </div>
                </div>

            </div>
            </form> 
        </div>
    </div>
    <!-- endsearch -->
    <!-- job_listing_area_start  -->
    <div class="job_listing_area">
        <div class="container">

            <div class="job_lists">
                <div class="row">
                    <div class="col-lg-10 col-md-10" style="height: 16rem;margin-bottom: 20rem;" >
                        {% for d in doctor %}
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div >
                                    {% if detail.image %}
                                    <img class="img-circle" src="{{ d.image.url }}" alt="" width="100" height="100">
        
                                    {% else %}
                                    <img class="img-circle" src="{% static 'img/candiateds/2.png' %}" alt="" width="100" height="100">
        
                                    {% endif %}
                                    
                                </div>
                                <div class="jobs_conetent">
                                    <a href="{% url 'accounts:doctor_details' d.slug %}"><h5>دكتور </h5> {{ d.title }} </a>
                                    <h6>{{ d.subtitle }}</h6>
                                    
                                    <div class="links_locat">
                                        <div class="location">
                                            <p> <i class="fas fa-briefcase-medical"></i> دكتور <span style="color: blue;"> {{ d.job_name }} </span> متخصص في <span style="color: blue;"> {{ d.department }} </span></p>
                                            <p> <i class="fa fa-map-marker"></i>{{d.address}} : {{ d.provenece }}</p>
                                            <p> <i class="fa fa-map-marker"></i> الكشف : <span style="color: blue;"> {{ d.price }} </span> جنية</p>
                                            <p> <i class="fa fa-clock-o"></i> مدة الانتظار : <span style="color: blue;">{{d.working_time}}</span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i> عدد ساعات العمل : <span style="color: blue;">{{d.working_hour}}</span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i>سعر المكالمه العادية  :<span style="color: blue;"> {{d.number}} </span>  </p>


                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="boxed-btn3" href="">حجز كشف</a>
                                </div>

                                <div class="rating">
                                    <div class="text-warning">
                                        <!-- to make image category for clinic image -->
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        </div>
                                    <div class="rating" >
                                        <h5>تقييم الدكتور</h5>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        {% endfor %}
                    </div>


                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
</div>
    <!-- featured_candidates_area_start  -->
    <!-- <div class="featured_candidates_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section_title text-center mb-40">
                        <h3>المرشحين المميزين</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="candidate_active owl-carousel">
                        <div class="single_candidates text-center">
                            <div class="thumb">
                                <img class="img-circle " src="img/candiateds/2.png" alt="" >
                                
                            </div>
                            <a href="" ><h4 >الاسم</h4></a>
                            <p>  التخصص</p>
                            <div class="best-rating">
                                <div class="text-warning">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        
                                </div>
                                <div class="best-rating" >
                                    <h5>تقييم الدكتور</h5>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div> -->
    <!-- featured_candidates_area_end  -->


{% endblock body %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}

<div dir="rtl">
<div class="container">
    <div class="signup">
        <div class="col-md-9" >
            <form method="POST">
                <h4 class="auth-header">تسجيل الدخول</h4>
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary" > تسحيل الدخول</button>
            </form>
        </div>
    </div>
</div>
</div>

{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}

<div dir="rtl">
<div class="container">
    <div class="signup">

        <div class="col-md-9" >
            <form method="POST">
                <h4 class="auth-header">أنشاء حساب جديد</h4>
                {% csrf_token %}
                {% bootstrap_form forms %}
                <button type="submit" class="btn btn-primary">التسجيل</button>

            </form>
        </div>
    </div>
</div>
</div>

{% endblock body %}

accounts/templates/accounts/updata_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static  %}
{% block body %}

<div dir="rtl">
<div class="container">
    <div class="signup">

    <div class="col-md-9" >
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form update %}
            <button type="submit" class="btn btn-primary" >تحديث</button>
        </form>
    </div>
    </div>
</div>
</div>

{% endblock body %}

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">



    <title>Vezeta</title>

    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'}% ">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%} ">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%} ">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'%} ">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%} ">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%} ">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%} ">
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%} ">
    <link rel="stylesheet" href="{% static 'css/slicknav.css'%} ">

    <link rel="stylesheet" href="{% static 'css/style.css'%} ">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>

<!-- header-start -->
<header>
<div class="header-area ">
    <div id="sticky-header" class="main-header-area">
        <div class="container-fluid " style="background-color: rgba(0, 29, 56, 0.8);" >
            <div class="header_bottom_border">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-2">
                        <div class="logo">
                            <a href="{% url 'accounts:index'  %}">
                                <img src="{% static 'img/logo2.png' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-7">
                        <div class="main-menu  d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a href="{% url 'accounts:index' %}">احجز دكتورك</a></li>|
                                    <li><a href="">المقالات</a></li>|
                                    {% if user.is_authenticated %}
                                    <li><a href="{% url 'accounts:profile' %}">الصفحه الشخصيه </a></li>|
                                    {% endif %}
                                    <li><a href="contact.html">اتصل بنا</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                        <div class="Appointment">
                            
                            <div class="phone_num d-none d-xl-block"></div>
                            {% if user.is_authenticated %}
                            <div class="d-none d-lg-block">
                                <a class="boxed-btn3" style="margin-right:10px;" href="{% url 'accounts:update' %}">قدم نفسك</a>
                            </div>
                            <div class="d-none d-lg-block">
                                <a class="boxed-btn3" href="{% url 'accounts:logout' %}"> تسجيل الخروج</a>
                            </div>
                            {% else %}
                            
                            <div class="phone_num d-none d-xl-block">
                                <a class="boxed-btn3" href="{% url 'accounts:login' %}">سجل الدخول</a>
                            </div>
                            <div class="d-none d-lg-block">
                                <a class="boxed-btn3" style="background-color: crimson;" href="{% url 'accounts:register' %}">التسجيل</a>
                            </div>
                            {% endif %}
                            
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</header>
<!-- header-end -->


{% block body %}




{% endblock body %}


<!-- footer start -->
<footer class="footer">
    <div class="footer_top">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-md-6 col-lg-3">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                    <div class="footer_logo">
                        <a href="#">
                            <img src="{% static 'img/logo2.png' %}" alt="">
                        </a>
                    </div>
                    <p>
                        abdelrahman ibrahem <br>
                    </p>
                </div>
            </div>
            <div class="col-xl-2 col-md-6 col-lg-2">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                    <h3 class="footer_title">
                        ماذا عنا
                    </h3>
                    <ul>
                        <li><a href="#">من نحن </a></li>
                        <li><a href="#"> أسعارنا</a></li>
                        <li><a href="#">إستفسار</a></li>
                    </ul>
    
                </div>
            </div>
            <div class="col-xl-3 col-md-6 col-lg-3">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                    <h3 class="footer_title">
                        الخدمات
                    </h3>
                    <ul>
                        <li><a href="#">اعمالنا</a></li>
                        <li><a href="#">شركائنا</a></li>
                        <li><a href="#">الخصومات والمشاريع</a></li>
                        <li><a href="#">للإعلان</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xl-4 col-md-6 col-lg-4">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                    <h3 class="footer_title">
                        Subscribe
                    </h3>
                    <form action="#" class="newsletter_form">
                        <input type="text" placeholder="Enter your mail">
                        <button type="submit">Subscribe</button>
                    </form>
                    <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                        luckily.</p>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
    <div class="container">
        <div class="footer_border"></div>
        <div class="row">
            <div class="col-xl-12">
                <p class="copy_right text-center">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
    </div>
    </footer>
    <!--/ footer end  -->
    
    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %} "></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %} "></script>
    <script src="{% static 'js/popper.min.js' %} "></script>
    <script src="{% static 'js/bootstrap.min.js' %} "></script>
    <script src="{% static 'js/owl.carousel.min.js'% } "></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %} "></script>
    <script src="{% static 'js/ajax-form.js' %} "></script>
    <script src="{% static 'js/waypoints.min.js' %} "></script>
    <script src="{% static 'js/jquery.counterup.min.js' %} "></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js'% } "></script>
    <script src="{% static 'js/scrollIt.js' %} "></script>
    <script src="{% static 'js/jquery.scrollUp.min.js'% } "></script>
    <script src="{% static 'js/wow.min.js' %} "></script>
    <script src="{% static 'js/nice-select.min.js'% } "></script>
    <script src="{% static 'js/jquery.slicknav.min.js'% } "></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %} "></script>
    <script src="{% static 'js/plugins.js' %} "></script>
    <script src="{% static 'js/gijgo.min.js'% } "></script>
    
    
    
    <!--contact js-->
    <script src="{% static 'js/contact.js' %} "></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %} "></script>
    <script src="{% static 'js/jquery.form.js' %} "></script>
    <script src="{% static 'js/jquery.validate.min.js' %} "></script>
    <script src="{% static 'js/mail-script.js' %} "></script>
    
    
    <script src="{% static 'js/main.js' %} "></script>
    </body>
    
    </html>